### ISSUE TITLE
Execution stops at var shardMap = smm.GetShardMap("TenentIDShardMap");

### ISSUE THREAD

**Issue by dhmuralikrishna** [Azure/elastic-db-tools#145] opened 2016-10-20 19:02 UTC
Issue with using the code in MVC. Action.. Same code works fine in console application. 

 string connectionString = @"Data Source=myserver;Initial Catalog=somecatalog;Integrated Security=False;User ID=cmsadmin;Password=mypassowrd;Connect Timeout=30;Application Name=ESC_SKv1.0";

```
        ShardMapManager smm = ShardMapManagerFactory.GetSqlShardMapManager(connectionString, ShardMapManagerLoadPolicy.Lazy);

        var shardMap = smm.GetShardMap("TenentIDShardMap");
```

**Comment by jaredmoo** [comment] 2016-10-20 19:06
Which release are you using? I suspect that this may be a deadlock caused by use of `Task.Wait()`/`Task.Result` which may be fixed by https://github.com/Azure/elastic-db-tools/releases/tag/v1.3.3

**Comment by dhmuralikrishna** [comment] 2016-10-20 19:15
Application framework MVC 4.6.1 and elastic sql client nuget 1.3.3

**Comment by dhmuralikrishna** [comment] 2016-10-21 15:39
Any one has an working example with MVC.

**Comment by dhmuralikrishna** [comment] 2016-10-25 21:02
Hello, please advice it's a BIG show stopper for us. Designed everything based Elastic SQL now it's not working.

**Comment by jaredmoo** [comment] 2016-10-25 21:08
Are you able to debug and provide a call stack of where it is stuck? and/or can you provide a minimal standalone repro that I can run and debug myself? Thanks :)

**Comment by dhmuralikrishna** [comment] 2016-10-25 23:58
Steps are simple. 
Create a Console Application(.NET 4.6) and 
add  package Microsoft.Azure.SqlDatabase.ElasticScale.Client
Past these 3 lines in main method.  it will work. 3 statements successfully executes. 

Do the same with MVC 6. Create a project add package Microsoft.Azure.SqlDatabase.ElasticScale.Client.  past the same 3 lines inside MVC action. execution hangs at  3rd statement (GetListShardMap).  No Error/Exception, just execution stops at 3rd statement. 

```

 string connectionString = @"Data Source=cmssaasdev.database.windows.net;Initial Catalog=CMS_ShardMapManagerDb;Integrated Security=False;User ID=cmsadmin;Password=Krishna417!;Connect Timeout=30;Application Name=ESC_SKv1.0";

ShardMapManager smm = ShardMapManagerFactory.GetSqlShardMapManager(connectionString, ShardMapManagerLoadPolicy.Lazy);

 ListShardMap<int> shardMap = smm.GetListShardMap<int>("TenentIDShardMap");
```

**Comment by raveeram** [comment] 2016-10-26 00:22
You might want to scrub your connection string. Also, I don't think ASP.NET is supported (atleast we didn't test against it). You could also turn on logging. 
Trace source names here: https://github.com/Azure/elastic-db-tools/blob/master/Src/ElasticScale.Client/ShardManagement/Logging/TraceSourceConstants.cs. 
I don't work on this project currently, so these are just suggestions.

**Comment by dhmuralikrishna** [comment] 2016-10-26 03:15
I debugged source code and found it is stooping at 

Class PerfCounterInstance  line 124.

if (!PerformanceCounterCategory.Exists(PerformanceCounters.ShardManagementPerformanceCounterCategory))

**Comment by jaredmoo** [comment] 2016-10-26 03:51
Glad you were able to get unblocked. I'll leave the issue open so we can come back and get this fixed.

**Comment by r0bturner** [comment] 2017-11-06 11:51
I'm having this issue exactly how @dhmuralikrishna describes. Downgrading to 1.2 works for me as well. 
However this issue occurs on my work machine but not on my home machine.

Is there any more info on this issue?

**Comment by r0bturner** [comment] 2017-11-06 14:39
Found the following online:

https://blogs.msdn.microsoft.com/webdev/2013/11/15/asp-net-performance-performance-counters-on-windows-client-iis-express/#comments

My work machine is windows 7 and home machine is windows 10. If I run the web app on Local IIS on my windows 7 machine I'm able to use the latest library.

**Comment by jaredmoo** [comment] 2017-11-06 16:29
Sounds like we need a feature switch to optionally disable perf counters. e.g. `ShardMapManager.EnablePerformanceCounters = false;`. Would that work?

**Comment by jaredmoo** [comment] 2017-11-06 16:32
Or perhaps some way to detect whether the APIs we call will be supported. If there was an exception to catch that would also work, but it sounds like this is a hang.

**Comment by r0bturner** [comment] 2017-11-06 20:52
Being able to disable performance counters would work however I'm not sure I would have been able to easily identity that as a setting to apply. So throwing some kind of exception would be ideal as you're correct in saying that right now it hangs.

**Comment by stuartpa** [comment] 2023-10-12 08:22
I think this is an issue on Windows 7 (per https://blogs.msdn.microsoft.com/webdev/2013/11/15/asp-net-performance-performance-counters-on-windows-client-iis-express).  Closing as Windows 7 is probably not being used to run this library any more.

**Closed by stuartpa** 2023-10-12 08:22 UTC
